(function(){
  "use strict";
  const MODES={unit:{name:"ぴったり単位",icon:"🎯",desc:"場面に合う単位を選ぶ",color:"#0f766e"},conversion:{name:"単位チェンジ",icon:"🔄",desc:"単位を変えて表す",color:"#2563a8"},repair:{name:"データ修理",icon:"🛠️",desc:"変な単位を見つけて直す",color:"#d56b28"},compare:{name:"そろえてくらべる",icon:"⚖️",desc:"単位をそろえて比べる",color:"#7c4ab0"},decimal:{name:"小数研究",icon:"🔬",desc:"小数を使って表す",color:"#bd3e67"}};
  const BADGES=[{id:"start",emoji:"🥉",name:"単位研究スタート",desc:"はじめて10問を研究する"},...Object.entries(LABS).map(([id,l])=>({id:`lab-${id}`,emoji:l.icon,name:`${l.name}研究員`,desc:"5つの研究モードをすべて体験する"})),{id:"perfect",emoji:"💯",name:"全問正解研究員",desc:"10問すべて正解する"},{id:"hundred",emoji:"🧪",name:"100問研究員",desc:"累計100問を研究する"},{id:"master",emoji:"🏆",name:"単位はかせ",desc:"6つのラボをすべて修了する"}];
  const KEY="unitLab-all-v2",OLD_KEY="unitLab-length-v1";
  const defaults={xp:0,total:0,correct:0,plays:0,seen:[],weak:[],badges:[],modeStats:{},best:{}};
  let saved=load(),currentLab="length",session=null;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  function load(){
    try{const now=localStorage.getItem(KEY);if(now)return{...defaults,...JSON.parse(now)};const old=JSON.parse(localStorage.getItem(OLD_KEY)||"null");if(!old)return{...defaults};const prefix=id=>{const m=String(id).match(/^(unit|conversion|repair|compare|decimal)-(\d+)$/);return m?`length:${m[1]}:${m[2]}`:id};const modeStats={};Object.entries(old.modeStats||{}).forEach(([m,v])=>modeStats[`length:${m}`]=v);const best={};Object.entries(old.best||{}).forEach(([m,v])=>best[`length:${m}`]=v);return{...defaults,xp:old.xp||0,total:old.total||0,correct:old.correct||0,plays:old.plays||0,seen:(old.seen||[]).map(prefix),weak:(old.weak||[]).map(prefix),badges:(old.badges||[]).includes("start")?["start"]:[],modeStats,best};}catch{return{...defaults};}
  }
  function save(){localStorage.setItem(KEY,JSON.stringify(saved));updateHeader();}
  function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:"smooth"});}
  function statKey(lab,mode){return`${lab}:${mode}`;}
  function updateHeader(){
    $('#xpValue').textContent=saved.xp;$('#badgeCount').textContent=saved.badges.length;$('#badgeTotal').textContent=BADGES.length;$('#totalRecord').textContent=`学習 ${saved.total}問　正解 ${saved.correct}問`;
    const all=saved.weak.length;$('#allWeakCount').textContent=all;$('#allTrainingBtn').disabled=!all;
    const own=saved.weak.filter(id=>id.startsWith(`${currentLab}:`)).length;$('#trainingText').textContent=own?`にがて問題が ${own}問 あります。正解すると特訓リストから外れます。`:"まちがえた問題がここに集まります。";$('#trainingBtn').disabled=!own;
  }
  function renderLabs(){
    $('#labGrid').innerHTML=Object.entries(LABS).map(([id,l])=>{const done=Object.keys(MODES).filter(m=>(saved.modeStats[statKey(id,m)]?.plays||0)>0).length;const weak=saved.weak.filter(x=>x.startsWith(`${id}:`)).length;return`<button class="lab-card" data-lab="${id}" style="--lab:${l.color}"><span class="lab-emoji">${l.icon}</span><h3>${l.name}</h3><p>${l.desc}</p><div class="lab-progress"><i style="width:${done/5*100}%"></i></div><small>研究 ${done}/5${weak?`　・　にがて ${weak}問`:""}</small></button>`}).join('');
    $$('.lab-card').forEach(b=>b.addEventListener('click',()=>openLab(b.dataset.lab)));
  }
  function openLab(id){currentLab=id;const l=LABS[id];$('#labLabel').textContent=l.name;$('#heroIcon').textContent=l.icon;$('#heroTitle').textContent=l.name;$('#heroDescription').textContent=l.detail;$('#heroCharacter').src=l.character;$('#pageBg').style.backgroundImage=`linear-gradient(rgba(238,249,247,.9),rgba(238,249,247,.96)),url("${l.bg}")`;renderModes();renderHint();updateHeader();show('homeScreen');}
  function goLabs(){renderLabs();$('#labLabel').textContent="総合ラボ";$('#pageBg').style.backgroundImage='linear-gradient(rgba(238,249,247,.89),rgba(238,249,247,.95)),url("https://tt-sensei.github.io/navi-character-/assets/web/backgrounds/daily/daily-classroom.webp")';updateHeader();show('labScreen');}
  function renderModes(){
    const total=Object.keys(MODES).reduce((n,m)=>n+(saved.modeStats[statKey(currentLab,m)]?.total||0),0);$('#labRecord').textContent=`このラボで ${total}問研究`;
    $('#modeGrid').innerHTML=Object.entries(MODES).map(([id,m])=>{const s=saved.modeStats[statKey(currentLab,id)]||{plays:0,correct:0,total:0};return`<button class="mode-card" data-mode="${id}" style="--mode:${m.color}"><span class="mode-icon">${m.icon}</span><h3>${m.name}</h3><p>${m.desc}</p><small>${s.plays?`${s.plays}回・正解 ${s.correct}/${s.total}`:"20問から10問出題"}</small></button>`}).join('');$$('.mode-card').forEach(b=>b.addEventListener('click',()=>start(currentLab,b.dataset.mode,false,false)));
  }
  function renderHint(){const l=LABS[currentLab];$('#hintTitle').textContent=`${l.name}の単位一覧`;$('#unitRelations').innerHTML=l.relations.map(x=>`<div><b>${x}</b></div>`).join('');$('#unitSense').innerHTML=l.sense.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span><small>${x[2]}</small></div>`).join('');$('#hintNote').textContent=l.note;}
  function renderBadges(){$('#badgeGrid').innerHTML=BADGES.map(b=>`<article class="badge-card ${saved.badges.includes(b.id)?"earned":""}"><div class="badge-emoji">${saved.badges.includes(b.id)?b.emoji:"🔒"}</div><h3>${b.name}</h3><p>${b.desc}</p></article>`).join('');}
  function allQuestions(lab){const labs=lab?[lab]:Object.keys(LABS);return labs.flatMap(l=>Object.values(LAB_DATA[l]).flat());}
  function chooseQuestions(lab,mode){const list=[...LAB_DATA[lab][mode]],seen=new Set(saved.seen),weak=new Set(saved.weak);list.sort((a,b)=>score(b)-score(a)||Math.random()-.5);function score(q){return(!seen.has(q.id)?4:0)+(weak.has(q.id)?2:0)+Math.random();}return list.slice(0,10);}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function start(lab,mode,training,globalTraining){
    let questions;if(training){questions=allQuestions(globalTraining?null:lab).filter(q=>saved.weak.includes(q.id));if(!questions.length)return;shuffle(questions);}else questions=chooseQuestions(lab,mode);
    session={lab,mode,training,globalTraining,questions,index:0,correct:0,answered:false,lastLab:lab,lastMode:mode};$('#retryBtn').hidden=false;$('#stopTraining').hidden=!training;show('playScreen');renderQuestion();
  }
  function current(){return session.questions[session.index%session.questions.length];}
  function renderQuestion(){const q=current(),m=MODES[q.mode],l=LABS[q.lab];currentLab=q.lab;renderHint();session.answered=false;$('#playMode').textContent=session.training?`にがて特訓・${l.name}`:`${l.name}・${m.name}`;$('#progressText').textContent=session.training?`特訓 ${session.index+1}問目`:`${session.index+1} / ${session.questions.length}`;$('#progressBar').style.width=session.training?`${Math.min(100,((session.index%10)+1)*10)}%`:`${(session.index+1)/session.questions.length*100}%`;$('#sceneIcon').textContent=l.icon;$('#instruction').textContent=q.instruction;$('#questionText').textContent=q.question;$('#feedback').className='feedback';$('#feedback').textContent='';$('#sessionScore').textContent=`正解 ${session.correct}`;
    if(q.mode==='repair')renderChoices([{v:'odd',t:'おかしい'},{v:'ok',t:'おかしくない'}],repairJudge);else if(q.choices)renderChoices(q.choices.map(v=>({v:v==='＝'?'=':v,t:v})),(v,b)=>answer(q,v,b));else renderInputs(q);
  }
  function renderChoices(items,fn){$('#answerArea').innerHTML=items.map(x=>`<button class="choice" data-value="${x.v}">${x.t}</button>`).join('');$$('.choice').forEach(b=>b.addEventListener('click',()=>fn(b.dataset.value,b)));}
  function renderInputs(q){$('#answerArea').innerHTML=q.answers.map((_,i)=>`<label><input inputmode="decimal" aria-label="答え" autocomplete="off"><span>${q.question.split('□')[1]||''}</span></label>`).join('')+'<button class="primary submit">決定</button>';$('.submit').addEventListener('click',()=>{const vals=$$('#answerArea input').map(x=>numberValue(x.value));if(vals.some(Number.isNaN)){pulse($('#answerArea'));return;}answer(q,vals)});$$('#answerArea input').forEach(x=>x.addEventListener('keydown',e=>{if(e.key==='Enter')$('.submit').click()}));$('#answerArea input')?.focus();}
  function numberValue(v){const z='０１２３４５６７８９';return Number(v.trim().replace(/[０-９]/g,c=>z.indexOf(c)).replace(/[．，,]/g,'.'));}
  function repairJudge(v,btn){if(session.answered)return;const q=current(),ok=(v==='odd')===q.isOdd;if(!ok){finishAnswer(false,btn,q,`ものや場面の大きさを思いうかべよう。${q.explain}`);return;}btn.classList.add('correct');if(!q.isOdd){finishAnswer(true,btn,q,q.explain);return;}$('#instruction').textContent='数字はそのまま。どの単位に直す？';renderChoices(LABS[q.lab].units.map(x=>({v:x,t:x})),(u,b)=>answer(q,u,b));}
  function answer(q,value,button){if(session.answered)return;let ok;if(q.mode==='repair')ok=value===q.answer;else if(q.choices)ok=value===q.answer;else ok=q.answers.every((x,i)=>Math.abs(x-value[i])<1e-7);finishAnswer(ok,button,q,ok?q.explain:`正しくは「${formatAnswer(q)}」。${q.explain}`);}
  function formatAnswer(q){if(q.mode==='repair')return`${q.value}${q.answer}`;if(q.choices)return q.answer;if(q.answers)return q.answers.map(fmt).join('、');return q.answer;}
  function fmt(n){return Number.isInteger(n)?String(n):String(Math.round(n*1000000)/1000000);}
  function finishAnswer(ok,button,q,message){session.answered=true;$$('#answerArea button,#answerArea input').forEach(x=>x.disabled=true);if(button)button.classList.add(ok?'correct':'wrong');const fb=$('#feedback');fb.className=`feedback ${ok?'good':'bad'}`;fb.innerHTML=`${ok?'できた！ 数字と単位をセットで見られたね。':'おしい！ 単位の関係を確かめよう。'}<br><small>${message}</small><br><button class="primary next-btn">${session.training?'つぎの特訓へ':session.index===session.questions.length-1?'結果を見る':'つぎの問題'}</button>`;pulse(fb);session.correct+=ok?1:0;recordQuestion(q,ok);$('#sessionScore').textContent=`正解 ${session.correct}`;$('.next-btn').addEventListener('click',next);}
  function recordQuestion(q,ok){if(!saved.seen.includes(q.id))saved.seen.push(q.id);if(ok){saved.correct++;if(session.training)saved.weak=saved.weak.filter(x=>x!==q.id);}else if(!saved.weak.includes(q.id))saved.weak.push(q.id);saved.total++;save();}
  function next(){session.index++;if(session.training){const remaining=session.questions.filter(q=>saved.weak.includes(q.id));if(!remaining.length){finishTraining();return;}session.questions=remaining;session.index%=remaining.length;renderQuestion();return;}if(session.index>=session.questions.length)finishSession();else renderQuestion();}
  function finishTraining(){const xp=session.correct*5;saved.xp+=xp;save();$('#resultTitle').textContent='にがて特訓 完了！';$('#resultMedal').textContent='🎯';$('#resultScore').textContent=`${session.correct}問`;$('#resultRate').textContent='克服！';$('#resultXp').textContent=`+${xp}`;$('#resultMessage').textContent='にがて問題をすべて解き直しました。よくねばり強く研究したね！';$('#newBadge').hidden=true;$('#retryBtn').hidden=true;show('resultScreen');}
  function finishSession(){const lab=session.lab,mode=session.mode,total=session.questions.length,rate=Math.round(session.correct/total*100),xp=session.correct*10+(session.correct===10?30:0),newOnes=[],key=statKey(lab,mode);saved.xp+=xp;saved.plays++;saved.modeStats[key]=saved.modeStats[key]||{plays:0,correct:0,total:0};saved.modeStats[key].plays++;saved.modeStats[key].correct+=session.correct;saved.modeStats[key].total+=total;saved.best[key]=Math.max(saved.best[key]||0,session.correct);award('start',newOnes);if(session.correct===10)award('perfect',newOnes);if(saved.total>=100)award('hundred',newOnes);if(Object.keys(MODES).every(m=>(saved.modeStats[statKey(lab,m)]?.plays||0)>0))award(`lab-${lab}`,newOnes);if(Object.keys(LABS).every(l=>saved.badges.includes(`lab-${l}`)))award('master',newOnes);save();$('#resultTitle').textContent=`${MODES[mode].name} 研究完了！`;$('#resultMedal').textContent=rate===100?'🏆':rate>=70?'🥇':'🔬';$('#resultScore').textContent=`${session.correct} / ${total}`;$('#resultRate').textContent=`${rate}%`;$('#resultXp').textContent=`+${xp}`;$('#resultMessage').textContent=rate===100?'全問正解！ 単位感覚がしっかり育っています。':rate>=70?'いい研究でした。まちがえた問題は、にがて特訓で確かめよう。':'単位一覧を見ながらで大丈夫。場面の大きさを思いうかべよう。';const nb=$('#newBadge');if(newOnes.length){nb.hidden=false;nb.innerHTML='<b>新しいバッジ！</b><br>'+newOnes.map(id=>{const b=BADGES.find(x=>x.id===id);return`${b.emoji} ${b.name}`}).join('<br>');}else nb.hidden=true;show('resultScreen');}
  function award(id,list){if(!saved.badges.includes(id)){saved.badges.push(id);list.push(id);}}
  function pulse(el){el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop');}
  function quitPlay(){session?.globalTraining?goLabs():openLab(session?.lab||currentLab);}
  $$('.hint-open').forEach(b=>b.addEventListener('click',()=>$('#hintDialog').showModal()));$('#hintClose').addEventListener('click',()=>$('#hintDialog').close());$('#hintDialog').addEventListener('click',e=>{if(e.target===$('#hintDialog'))$('#hintDialog').close();});
  $('#topBtn').addEventListener('click',goLabs);$('#labsBackBtn').addEventListener('click',goLabs);$('#quitBtn').addEventListener('click',quitPlay);$('#stopTraining').addEventListener('click',quitPlay);$('#resultHomeBtn').addEventListener('click',()=>openLab(session?.lastLab||currentLab));$('#resultLabsBtn').addEventListener('click',goLabs);$('#badgeBackBtn').addEventListener('click',goLabs);$('#badgeBtn').addEventListener('click',()=>{renderBadges();show('badgeScreen')});$('#trainingBtn').addEventListener('click',()=>start(currentLab,null,true,false));$('#allTrainingBtn').addEventListener('click',()=>start(null,null,true,true));
  $('#resumeBtn').addEventListener('click',()=>{const next=Object.keys(MODES).find(m=>!(saved.modeStats[statKey(currentLab,m)]?.plays))||Object.keys(MODES).sort((a,b)=>(saved.best[statKey(currentLab,a)]||0)-(saved.best[statKey(currentLab,b)]||0))[0];start(currentLab,next,false,false)});$('#retryBtn').addEventListener('click',()=>session.training?start(session.lastLab,null,true,session.globalTraining):start(session.lastLab,session.lastMode,false,false));
  renderLabs();updateHeader();
})();
