(function(){
  "use strict";
  const MODES={unit:{name:"ぴったり単位",icon:"🎯",desc:"場面に合う単位を選ぶ",color:"#0f766e"},conversion:{name:"単位チェンジ",icon:"🔄",desc:"単位を変えて表す",color:"#2563a8"},repair:{name:"データ修理",icon:"🛠️",desc:"変な単位を見つけて直す",color:"#d56b28"},compare:{name:"そろえてくらべる",icon:"⚖️",desc:"単位をそろえて比べる",color:"#7c4ab0"},decimal:{name:"小数研究",icon:"🔬",desc:"小数を使って表す",color:"#bd3e67"}};

  // edu-assets の公開カタログで実在を確認した、共通45種＋算数25種。
  // web版があるため、学習画面では軽量WebPを優先して使う。
  const BADGE_ROOT="https://tt-sensei.github.io/edu-assets/assets/web/badges/";
  const ASSET_BADGE_IDS={
    common:["accuracy","adventurer","breakthrough","challenger","champion","clear","combo","comeback","connection","courage","creative","curiosity","deep-thinker","discovery","explainer","explorer","first-step","focus","great-answer","growth","hard-worker","helper","hidden-badge","idea","independent","keep-going","knowledge","level-up","mastery","mission-complete","never-give-up","new-skill","observer","perfect","power-up","practice-master","problem-solver","review-master","special","speed","steady-progress","streak","teamwork","treasure","try-again"],
    math:["another-way","calculation","classification","fraction-sense","generalization","geometry","logical-thinking","math-compare","math-discovery","math-evidence","math-explainer","math-prediction","measurement","mental-math","number-line","number-sense","pattern","relationship","representation-link","reverse-thinking","simplify","spatial-sense","strategy","verification","visualize"]
  };
  const BADGE_LABELS={
    accuracy:"せいかく研究員",adventurer:"ラボぼうけん者",breakthrough:"ブレイクスルー",challenger:"チャレンジャー",champion:"チャンピオン",clear:"クリア記録",combo:"コンボ研究員",comeback:"カムバック",connection:"つながり発見",courage:"いどむ勇気",creative:"アイデア名人",curiosity:"なぜなぜ博士","deep-thinker":"じっくり思考家",discovery:"発見ハンター",explainer:"説明名人",explorer:"研究ぼうけん者","first-step":"はじめの一歩",focus:"集中研究員","great-answer":"ナイスアンサー",growth:"成長のしるし","hard-worker":"こつこつ研究員",helper:"たすけあい研究員","hidden-badge":"ひみつバッジ",idea:"ひらめき名人",independent:"ひとりで研究員","keep-going":"つづける力",knowledge:"知識コレクター","level-up":"レベルアップ",mastery:"マスター研究員","mission-complete":"ミッション達成","never-give-up":"あきらめない心","new-skill":"新しいスキル",observer:"よく見る名人",perfect:"パーフェクト","power-up":"パワーアップ","practice-master":"特訓マスター","problem-solver":"問題解決名人","review-master":"見直しマスター",special:"スペシャル発見",speed:"スピード研究員","steady-progress":"着実な一歩",streak:"連続研究員",teamwork:"チーム研究員",treasure:"研究のおたから","try-again":"もう一回の勇気",
    "another-way":"別の方法名人",calculation:"計算チェンジ名人",classification:"分類名人", "fraction-sense":"分数センス",generalization:"きまり発見",geometry:"図形研究員","logical-thinking":"論理的思考家","math-compare":"くらべる研究員","math-discovery":"算数発見家","math-evidence":"根拠を説明","math-explainer":"算数説明名人","math-prediction":"予想研究員",measurement:"はかる研究員","mental-math":"暗算研究員","number-line":"数直線研究員","number-sense":"数のセンス",pattern:"パターン発見",relationship:"関係発見", "representation-link":"表し方リンク", "reverse-thinking":"逆向き思考",simplify:"かんたんに整理", "spatial-sense":"空間センス",strategy:"作戦研究員",verification:"たしかめ研究員",visualize:"見える化研究員"
  };
  const BADGE_DESC={
    accuracy:"正答率を意識して研究する",adventurer:"いくつものラボをめぐる",breakthrough:"苦手な問題を乗りこえる",challenger:"むずかしい問題にも挑戦する",champion:"たくさんの研究を積み重ねる",clear:"研究チャレンジをクリアする",combo:"正解をつないでいく",comeback:"まちがいから研究を立て直す",connection:"数と単位のつながりに気づく",courage:"新しいモードに挑戦する",creative:"自分なりの考え方を試す",curiosity:"気になったことを調べる", "deep-thinker":"理由まで考えて答える",discovery:"新しい気づきを見つける",explainer:"答えの理由を説明する",explorer:"ラボを探検する", "first-step":"はじめての研究を記録する",focus:"集中して10問に取り組む", "great-answer":"すばらしい答えを出す",growth:"前よりできることを増やす", "hard-worker":"学習を何度も続ける",helper:"ヒントを上手に使う", "hidden-badge":"ひみつの条件を見つける",idea:"ひらめきを大切にする",independent:"自分の力で答えを導く", "keep-going":"まちがえても続けて研究する",knowledge:"単位の知識を集める", "level-up":"研究のレベルを上げる",mastery:"ラボの学びを深める", "mission-complete":"決めた研究をやり切る", "never-give-up":"何度でもやり直す", "new-skill":"新しい解き方を身につける",observer:"場面をよく観察する",perfect:"10問すべて正解する", "power-up":"研究の力を高める", "practice-master":"にがて特訓を完了する", "problem-solver":"問題を整理して解決する", "review-master":"まちがいを見直して直す",special:"特別な研究成果を得る",speed:"すばやく正確に答える", "steady-progress":"少しずつ着実に進む",streak:"研究を連続して続ける",teamwork:"NAVIといっしょに研究する",treasure:"研究の宝物を集める", "try-again":"もう一度挑戦する",
    "another-way":"別の表し方を考える",calculation:"単位変換を計算する",classification:"単位を仲間分けする", "fraction-sense":"分数の感覚をつかむ",generalization:"きまりを見つける",geometry:"図形の広さを考える", "logical-thinking":"順序立てて考える", "math-compare":"単位をそろえて比べる", "math-discovery":"算数の発見をする", "math-evidence":"数を根拠に説明する", "math-explainer":"算数の考えを伝える", "math-prediction":"結果を予想する",measurement:"量を正しくはかる", "mental-math":"頭の中で計算する", "number-line":"数直線で考える", "number-sense":"数の大きさを感じる",pattern:"きまりを見抜く",relationship:"量の関係を見つける", "representation-link":"表現を行き来する", "reverse-thinking":"逆から確かめる",simplify:"式を整理する", "spatial-sense":"広さや位置を感じる",strategy:"解き方を選ぶ",verification:"答えをたしかめる",visualize:"図やイメージで考える"
  };
  const ASSET_BADGES=Object.entries(ASSET_BADGE_IDS).flatMap(([category,ids])=>ids.map(id=>({id:`${category}:${id}`,category,assetId:id,image:`${BADGE_ROOT}${category}/${id}/badge.webp`,emoji:"🏅",name:BADGE_LABELS[id]||id,desc:BADGE_DESC[id]||"研究を積み重ねて獲得する"})));
  const LEGACY_BADGES=[{id:"start",emoji:"🥉",name:"単位研究スタート",desc:"はじめて10問を研究する",image:`${BADGE_ROOT}common/first-step/badge.webp`},...Object.entries(LABS).map(([id,l])=>({id:`lab-${id}`,emoji:l.icon,name:`${l.name}研究員`,desc:"5つの研究モードをすべて体験する",image:`${BADGE_ROOT}math/measurement/badge.webp`})),{id:"perfect",emoji:"💯",name:"全問正解研究員",desc:"10問すべて正解する",image:`${BADGE_ROOT}common/perfect/badge.webp`},{id:"hundred",emoji:"🧪",name:"100問研究員",desc:"累計100問を研究する",image:`${BADGE_ROOT}common/mission-complete/badge.webp`},{id:"master",emoji:"🏆",name:"単位はかせ",desc:"6つのラボをすべて修了する",image:`${BADGE_ROOT}common/mastery/badge.webp`}];
  const BADGES=[...LEGACY_BADGES,...ASSET_BADGES];
  const KEY="unitLab-all-v2",OLD_KEY="unitLab-length-v1";
  const NAVI_SCENES=["groups/learning/group-learning-pair-measure-shadow.webp","groups/learning/group-learning-science-experiment.webp","groups/learning/group-learning-pair-observation.webp","groups/learning/group-learning-pair-tablet.webp","groups/learning/group-learning-social-map.webp","groups/learning/group-learning-science-observation.webp"].map(x=>`https://tt-sensei.github.io/navi-character-/assets/web/${x}`);
  const defaults={xp:0,total:0,correct:0,plays:0,seen:[],weak:[],badges:[],modeStats:{},best:{},soundOn:true};
  const EDU_FALLBACK_EVENTS={CORRECT:"edu:correct",WRONG:"edu:wrong",SCREEN_CHANGE:"edu:screenchange",COMPLETE:"edu:complete",STORAGE_SAVE:"edu:storagesave",BADGE:"edu:badge"};
  let eduEvents=EDU_FALLBACK_EVENTS,eduStorage=null,eduBadgeManager=null,soundList=[],currentScreen="",audioCtx=null;
  let saved=load(),currentLab="length",session=null;
  saved.soundOn=saved.soundOn!==false;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];

  // edu-kitは実行ライブラリ1本ではなく、用途別の共通資産を組み合わせる設計。
  // 公開カタログで確認した実在エントリを、失敗しても教材が止まらない形で読み込む。
  const eduComponentsReady=import("https://tt-sensei.github.io/edu-components/index.js").then(mod=>{
    eduEvents=mod.EDU_EVENTS||EDU_FALLBACK_EVENTS;
    if(mod.StorageManager){
      eduStorage=new mod.StorageManager("unit-lab",{eventTarget:document});
      const managed=eduStorage.load("state",null);
      if(managed&&typeof managed==="object"&&!localStorage.getItem(KEY)){saved={...defaults,...managed};saved.soundOn=saved.soundOn!==false;}
      eduStorage.save("state",saved);
    }
    if(mod.BadgeManager&&eduStorage){
      eduBadgeManager=new mod.BadgeManager({badges:BADGES,storage:eduStorage,storageKey:"badges",eventTarget:document});
      const managedBadges=eduBadgeManager.getAwarded();
      if(managedBadges.length){saved.badges=[...new Set([...saved.badges,...managedBadges])];}
      saved.badges.forEach(id=>{if(!eduBadgeManager.has(id))eduBadgeManager.award(id);});
      save();
    }
    document.documentElement.dataset.eduKit="ready";
    updateHeader();renderLabs();
    window.dispatchEvent(new CustomEvent("edu-kit-ready"));
    return mod;
  }).catch(()=>{document.documentElement.dataset.eduKit="fallback";return null;});
  const soundRecipesReady=import("https://tt-sensei.github.io/sounds-recipe-/sounds.js").then(mod=>{soundList=Array.isArray(mod.soundList)?mod.soundList:[];return soundList;}).catch(()=>[]);
  window.EDU_KIT_STATUS={components:eduComponentsReady,sounds:soundRecipesReady,assets:"https://tt-sensei.github.io/edu-assets/"};
  function emitEdu(type,detail={}){const name=eduEvents[type]||EDU_FALLBACK_EVENTS[type];if(name)document.dispatchEvent(new CustomEvent(name,{detail}));}
  function playEffect(target,className){if(window.EduEffects?.play)window.EduEffects.play(target,className);else if(target){target.classList.remove(className);void target.offsetWidth;target.classList.add(className);}}
  function load(){
    try{const now=localStorage.getItem(KEY);if(now)return{...defaults,...JSON.parse(now)};const old=JSON.parse(localStorage.getItem(OLD_KEY)||"null");if(!old)return{...defaults};const prefix=id=>{const m=String(id).match(/^(unit|conversion|repair|compare|decimal)-(\d+)$/);return m?`length:${m[1]}:${m[2]}`:id};const modeStats={};Object.entries(old.modeStats||{}).forEach(([m,v])=>modeStats[`length:${m}`]=v);const best={};Object.entries(old.best||{}).forEach(([m,v])=>best[`length:${m}`]=v);return{...defaults,xp:old.xp||0,total:old.total||0,correct:old.correct||0,plays:old.plays||0,seen:(old.seen||[]).map(prefix),weak:(old.weak||[]).map(prefix),badges:(old.badges||[]).includes("start")?["start"]:[],modeStats,best};}catch{return{...defaults};}
  }
  function save(){localStorage.setItem(KEY,JSON.stringify(saved));if(eduStorage)eduStorage.save("state",saved);updateHeader();}
  function show(id){const from=currentScreen;$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));currentScreen=id;emitEdu("SCREEN_CHANGE",{from,to:id});window.scrollTo({top:0,behavior:"smooth"});}
  function statKey(lab,mode){return`${lab}:${mode}`;}
  function updateHeader(){
    $('#xpValue').textContent=saved.xp;$('#badgeCount').textContent=saved.badges.length;$('#badgeTotal').textContent=BADGES.length;$('#totalRecord').textContent=`学習 ${saved.total}問　正解 ${saved.correct}問`;$('#soundBtn').textContent=saved.soundOn?'🔊':'🔇';$('#soundBtn').setAttribute('aria-label',saved.soundOn?'音をオフにする':'音をオンにする');
    const all=saved.weak.length;$('#allWeakCount').textContent=all;$('#allTrainingBtn').disabled=!all;
    const own=saved.weak.filter(id=>id.startsWith(`${currentLab}:`)).length;$('#trainingText').textContent=own?`にがて問題が ${own}問 あります。正解すると特訓リストから外れます。`:"まちがえた問題がここに集まります。";$('#trainingBtn').disabled=!own;
  }
  function renderLabs(){
    $('#labGrid').innerHTML=Object.entries(LABS).map(([id,l])=>{const done=Object.keys(MODES).filter(m=>(saved.modeStats[statKey(id,m)]?.plays||0)>0).length;const weak=saved.weak.filter(x=>x.startsWith(`${id}:`)).length;return`<button class="lab-card" data-lab="${id}" style="--lab:${l.color}"><img class="lab-card-navi" src="${l.character}" alt=""><span class="lab-emoji">${l.icon}</span><h3>${l.name}</h3><p>${l.desc}</p><div class="lab-progress"><i style="width:${done/5*100}%"></i></div><small>研究 ${done}/5${weak?`　・　にがて ${weak}問`:""}</small></button>`}).join('');
    $$('.lab-card').forEach(b=>b.addEventListener('click',()=>openLab(b.dataset.lab)));
  }
  function openLab(id){currentLab=id;const l=LABS[id];$('#labLabel').textContent=l.name;$('#heroIcon').textContent=l.icon;$('#heroTitle').textContent=l.name;$('#heroDescription').textContent=l.detail;$('#heroCharacter').src=l.character;$('#pageBg').style.backgroundImage=`linear-gradient(rgba(238,249,247,.9),rgba(238,249,247,.96)),url("${l.bg}")`;renderModes();renderHint();updateHeader();show('homeScreen');}
  function goLabs(){renderLabs();$('#labLabel').textContent="総合ラボ";$('#pageBg').style.backgroundImage='linear-gradient(rgba(238,249,247,.89),rgba(238,249,247,.95)),url("https://tt-sensei.github.io/navi-character-/assets/web/backgrounds/daily/daily-classroom.webp")';updateHeader();show('labScreen');}
  function renderModes(){
    const total=Object.keys(MODES).reduce((n,m)=>n+(saved.modeStats[statKey(currentLab,m)]?.total||0),0);$('#labRecord').textContent=`このラボで ${total}問研究`;
    $('#modeGrid').innerHTML=Object.entries(MODES).map(([id,m])=>{const s=saved.modeStats[statKey(currentLab,id)]||{plays:0,correct:0,total:0};return`<button class="mode-card" data-mode="${id}" style="--mode:${m.color}"><span class="mode-icon">${m.icon}</span><h3>${m.name}</h3><p>${m.desc}</p><small>${s.plays?`${s.plays}回・正解 ${s.correct}/${s.total}`:"20問から10問出題"}</small></button>`}).join('');$$('.mode-card').forEach(b=>b.addEventListener('click',()=>start(currentLab,b.dataset.mode,false,false)));
  }
  function renderHint(){const l=LABS[currentLab];$('#hintTitle').textContent=`${l.name}の単位一覧`;$('#unitRelations').innerHTML=l.relations.map(x=>`<div><b>${x}</b></div>`).join('');$('#unitSense').innerHTML=l.sense.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span><small>${x[2]}</small></div>`).join('');$('#hintNote').textContent=l.note;}
  function renderBadges(){const earned=new Set(saved.badges);$('#badgeGrid').innerHTML=BADGES.map(b=>{const isEarned=earned.has(b.id);return`<article class="badge-card ${isEarned?"earned":""} ${b.category?`badge-${b.category}`:"badge-local"}"><div class="badge-visual">${b.image?`<img loading="lazy" src="${b.image}" alt="${isEarned?b.name:"未獲得バッジ"}">`:`<span class="badge-emoji">${isEarned?b.emoji:"🔒"}</span>`}<span class="badge-lock" aria-hidden="true">${isEarned?"":"🔒"}</span></div><h3>${b.name}</h3><p>${b.desc}</p>${b.category?`<small class="badge-source">edu-assets・${b.category==='math'?"算数":"共通"}</small>`:""}</article>`}).join('');}
  function allQuestions(lab){const labs=lab?[lab]:Object.keys(LABS);return labs.flatMap(l=>Object.values(LAB_DATA[l]).flat());}
  function chooseQuestions(lab,mode){const list=[...LAB_DATA[lab][mode]],seen=new Set(saved.seen),weak=new Set(saved.weak);list.sort((a,b)=>score(b)-score(a)||Math.random()-.5);function score(q){return(!seen.has(q.id)?4:0)+(weak.has(q.id)?2:0)+Math.random();}return list.slice(0,10);}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function start(lab,mode,training,globalTraining){
    let questions;if(training){questions=allQuestions(globalTraining?null:lab).filter(q=>saved.weak.includes(q.id));if(!questions.length)return;shuffle(questions);}else questions=chooseQuestions(lab,mode);
    session={lab,mode,training,globalTraining,questions,index:0,correct:0,answered:false,lastLab:lab,lastMode:mode};$('#retryBtn').hidden=false;$('#stopTraining').hidden=!training;sound('start');show('playScreen');renderQuestion();
  }
  function current(){return session.questions[session.index%session.questions.length];}
  function renderQuestion(){const q=current(),m=MODES[q.mode],l=LABS[q.lab];currentLab=q.lab;renderHint();session.answered=false;$('#naviCue').src=NAVI_SCENES[(session.index+session.correct)%NAVI_SCENES.length];$('#playMode').textContent=session.training?`にがて特訓・${l.name}`:`${l.name}・${m.name}`;$('#progressText').textContent=session.training?`特訓 ${session.index+1}問目`:`${session.index+1} / ${session.questions.length}`;$('#progressBar').style.width=session.training?`${Math.min(100,((session.index%10)+1)*10)}%`:`${(session.index+1)/session.questions.length*100}%`;$('#sceneIcon').textContent=l.icon;$('#instruction').textContent=q.instruction;$('#questionText').textContent=q.question;$('#feedback').className='feedback';$('#feedback').textContent='';$('#sessionScore').textContent=`正解 ${session.correct}`;
    if(q.mode==='repair')renderChoices([{v:'odd',t:'おかしい'},{v:'ok',t:'おかしくない'}],repairJudge);else if(q.choices)renderChoices(q.choices.map(v=>({v:v==='＝'?'=':v,t:v})),(v,b)=>answer(q,v,b));else renderInputs(q);
  }
  function renderChoices(items,fn){$('#answerArea').innerHTML=items.map(x=>`<button class="choice" data-value="${x.v}">${x.t}</button>`).join('');$$('.choice').forEach(b=>b.addEventListener('click',()=>fn(b.dataset.value,b)));}
  function renderInputs(q){$('#answerArea').innerHTML=q.answers.map((_,i)=>`<label><input inputmode="decimal" aria-label="答え" autocomplete="off"><span>${q.question.split('□')[1]||''}</span></label>`).join('')+'<button class="primary submit">決定</button>';$('.submit').addEventListener('click',()=>{const vals=$$('#answerArea input').map(x=>numberValue(x.value));if(vals.some(Number.isNaN)){pulse($('#answerArea'));return;}answer(q,vals)});$$('#answerArea input').forEach(x=>x.addEventListener('keydown',e=>{if(e.key==='Enter')$('.submit').click()}));$('#answerArea input')?.focus();}
  function numberValue(v){const z='０１２３４５６７８９';return Number(v.trim().replace(/[０-９]/g,c=>z.indexOf(c)).replace(/[．，,]/g,'.'));}
  function repairJudge(v,btn){if(session.answered)return;const q=current(),ok=(v==='odd')===q.isOdd;if(!ok){finishAnswer(false,btn,q,`ものや場面の大きさを思いうかべよう。${q.explain}`);return;}btn.classList.add('correct');if(!q.isOdd){finishAnswer(true,btn,q,q.explain);return;}$('#instruction').textContent='数字はそのまま。どの単位に直す？';renderChoices(LABS[q.lab].units.map(x=>({v:x,t:x})),(u,b)=>answer(q,u,b));}
  function answer(q,value,button){if(session.answered)return;let ok;if(q.mode==='repair')ok=value===q.answer;else if(q.choices)ok=value===q.answer;else ok=q.answers.every((x,i)=>Math.abs(x-value[i])<1e-7);finishAnswer(ok,button,q,ok?q.explain:`正しくは「${formatAnswer(q)}」。${q.explain}`);}
  function formatAnswer(q){if(q.mode==='repair')return`${q.value}${q.answer}`;if(q.choices)return q.answer;if(q.answers)return q.answers.map(fmt).join('、');return q.answer;}
  function fmt(n){return Number.isInteger(n)?String(n):String(Math.round(n*1000000)/1000000);}
  function finishAnswer(ok,button,q,message){session.answered=true;$$('#answerArea button,#answerArea input').forEach(x=>x.disabled=true);if(button)button.classList.add(ok?'correct':'wrong');sound(ok?'correct':'wrong');emitEdu(ok?'CORRECT':'WRONG',{answer:q.answer,correct:q.answer,isCorrect:ok,question:q.question,type:q.mode});const fb=$('#feedback');fb.className=`feedback ${ok?'good':'bad'}`;fb.innerHTML=`${ok?'できた！ 数字と単位をセットで見られたね。':'おしい！ 単位の関係を確かめよう。'}<br><small>${message}</small><br><button class="primary next-btn">${session.training?'つぎの特訓へ':session.index===session.questions.length-1?'結果を見る':'つぎの問題'}</button>`;playEffect(fb,ok?'effect-correct-pop':'effect-wrong-shake');pulse(fb);session.correct+=ok?1:0;recordQuestion(q,ok);$('#sessionScore').textContent=`正解 ${session.correct}`;$('.next-btn').addEventListener('click',next);}
  function recordQuestion(q,ok){if(!saved.seen.includes(q.id))saved.seen.push(q.id);if(ok){saved.correct++;if(session.training)saved.weak=saved.weak.filter(x=>x!==q.id);}else if(!saved.weak.includes(q.id))saved.weak.push(q.id);saved.total++;save();}
  function next(){session.index++;if(session.training){const remaining=session.questions.filter(q=>saved.weak.includes(q.id));if(!remaining.length){finishTraining();return;}session.questions=remaining;session.index%=remaining.length;renderQuestion();return;}if(session.index>=session.questions.length)finishSession();else renderQuestion();}
  function renderNewBadges(list){const nb=$('#newBadge');if(!list.length){nb.hidden=true;nb.textContent='';return;}nb.hidden=false;nb.innerHTML='<b>新しいバッジ！</b><div class="new-badge-list">'+list.map(id=>{const b=BADGES.find(x=>x.id===id);return b?`<span class="new-badge-item">${b.image?`<img src="${b.image}" alt="">`:b.emoji} ${b.name}</span>`:''}).join('')+'</div>';}
  function finishTraining(){const xp=session.correct*5,newOnes=[];saved.xp+=xp;award('common:practice-master',newOnes);award('common:never-give-up',newOnes);if(saved.weak.length===0)award('common:review-master',newOnes);save();emitEdu('COMPLETE',{type:'training',value:session.correct,result:{correct:session.correct}});sound('complete');$('#resultCharacter').src=NAVI_SCENES[session.correct%NAVI_SCENES.length];$('#resultTitle').textContent='にがて特訓 完了！';$('#resultMedal').textContent='🎯';$('#resultScore').textContent=`${session.correct}問`;$('#resultRate').textContent='克服！';$('#resultXp').textContent=`+${xp}`;$('#resultMessage').textContent='にがて問題をすべて解き直しました。よくねばり強く研究したね！';renderNewBadges(newOnes);$('#retryBtn').hidden=true;show('resultScreen');}
  function finishSession(){const lab=session.lab,mode=session.mode,total=session.questions.length,rate=Math.round(session.correct/total*100),xp=session.correct*10+(session.correct===10?30:0),newOnes=[],key=statKey(lab,mode);saved.xp+=xp;saved.plays++;saved.modeStats[key]=saved.modeStats[key]||{plays:0,correct:0,total:0};saved.modeStats[key].plays++;saved.modeStats[key].correct+=session.correct;saved.modeStats[key].total+=total;saved.best[key]=Math.max(saved.best[key]||0,session.correct);
    award('start',newOnes);award('common:first-step',newOnes);if(session.correct>=7)award('common:accuracy',newOnes);if(session.correct>0)award('common:great-answer',newOnes);if(session.correct===10){award('perfect',newOnes);award('common:perfect',newOnes);award('common:combo',newOnes);}else{award('common:try-again',newOnes);award('common:keep-going',newOnes);}if(saved.total>=100){award('hundred',newOnes);award('common:mission-complete',newOnes);}if(saved.total>=300)award('common:mastery',newOnes);if(saved.plays>=5)award('common:steady-progress',newOnes);if(saved.plays>=10)award('common:hard-worker',newOnes);
    const modeBadge={unit:'measurement',conversion:'calculation',repair:'verification',compare:'math-compare',decimal:'number-sense'}[mode];if(modeBadge)award(`math:${modeBadge}`,newOnes);const labComplete=Object.keys(MODES).every(m=>(saved.modeStats[statKey(lab,m)]?.plays||0)>0);if(labComplete){award(`lab-${lab}`,newOnes);award('common:clear',newOnes);award('common:discovery',newOnes);}const allLabsComplete=Object.keys(LABS).every(l=>Object.keys(MODES).every(m=>(saved.modeStats[statKey(l,m)]?.plays||0)>0));if(allLabsComplete){award('master',newOnes);award('common:champion',newOnes);award('common:treasure',newOnes);}if(saved.weak.length===0)award('common:review-master',newOnes);save();emitEdu('COMPLETE',{type:'session',value:rate,result:{lab,mode,correct:session.correct,total}});sound(session.correct===10?'complete':'finish');$('#resultCharacter').src=NAVI_SCENES[(session.correct+session.index)%NAVI_SCENES.length];$('#resultTitle').textContent=`${MODES[mode].name} 研究完了！`;$('#resultMedal').textContent=rate===100?'🏆':rate>=70?'🥇':'🔬';$('#resultScore').textContent=`${session.correct} / ${total}`;$('#resultRate').textContent=`${rate}%`;$('#resultXp').textContent=`+${xp}`;$('#resultMessage').textContent=rate===100?'全問正解！ 単位感覚がしっかり育っています。':rate>=70?'いい研究でした。まちがえた問題は、にがて特訓で確かめよう。':'単位一覧を見ながらで大丈夫。場面の大きさを思いうかべよう。';renderNewBadges(newOnes);show('resultScreen');}
  function award(id,list){if(!id||saved.badges.includes(id))return false;let managed=false;try{if(eduBadgeManager&&!eduBadgeManager.has(id)){managed=eduBadgeManager.award(id);}}catch(e){}saved.badges.push(id);list.push(id);if(!managed)emitEdu('BADGE',{id,badge:BADGES.find(x=>x.id===id)||{id},awardedCount:saved.badges.length});sound('badge');return true;}
  function sound(kind){if(!saved.soundOn)return;const recipeId={click:'click',start:'questionStart',correct:'correct',wrong:'softFail',badge:'badge',finish:'practice',complete:'mission'}[kind]||kind;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const recipe=soundList.find(x=>x.id===recipeId);if(recipe){recipe.play(audioCtx,.18);return;}const recipes={click:[[520,.045,0]],start:[[392,.07,0],[523,.08,.07]],correct:[[523,.08,0],[659,.1,.08],[784,.14,.18]],wrong:[[220,.12,0],[165,.18,.12]],badge:[[523,.08,0],[659,.08,.09],[784,.08,.18],[1047,.18,.27]],finish:[[523,.1,0],[659,.1,.11]],complete:[[523,.08,0],[659,.08,.09],[784,.08,.18],[1047,.24,.3]]};(recipes[kind]||recipes.click).forEach(([freq,dur,delay])=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=kind==='wrong'?'sawtooth':'sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioCtx.currentTime+delay);g.gain.exponentialRampToValueAtTime(.055,audioCtx.currentTime+delay+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+delay+dur);o.connect(g).connect(audioCtx.destination);o.start(audioCtx.currentTime+delay);o.stop(audioCtx.currentTime+delay+dur+.02);});}catch(e){/* 音が使えない環境でも学習は続けられる */}}
  function pulse(el){el.classList.remove('pop');void el.offsetWidth;el.classList.add('pop');}
  function quitPlay(){session?.globalTraining?goLabs():openLab(session?.lab||currentLab);}
  $$('.hint-open').forEach(b=>b.addEventListener('click',()=>$('#hintDialog').showModal()));$('#hintClose').addEventListener('click',()=>$('#hintDialog').close());$('#hintDialog').addEventListener('click',e=>{if(e.target===$('#hintDialog'))$('#hintDialog').close();});
  $('#topBtn').addEventListener('click',()=>{sound('click');goLabs()});$('#labsBackBtn').addEventListener('click',()=>{sound('click');goLabs()});$('#quitBtn').addEventListener('click',quitPlay);$('#stopTraining').addEventListener('click',quitPlay);$('#resultHomeBtn').addEventListener('click',()=>openLab(session?.lastLab||currentLab));$('#resultLabsBtn').addEventListener('click',goLabs);$('#badgeBackBtn').addEventListener('click',goLabs);$('#badgeBtn').addEventListener('click',()=>{sound('click');renderBadges();show('badgeScreen')});$('#soundBtn').addEventListener('click',()=>{saved.soundOn=!saved.soundOn;save();if(saved.soundOn)sound('click')});$('#trainingBtn').addEventListener('click',()=>start(currentLab,null,true,false));$('#allTrainingBtn').addEventListener('click',()=>start(null,null,true,true));
  $('#resumeBtn').addEventListener('click',()=>{const next=Object.keys(MODES).find(m=>!(saved.modeStats[statKey(currentLab,m)]?.plays))||Object.keys(MODES).sort((a,b)=>(saved.best[statKey(currentLab,a)]||0)-(saved.best[statKey(currentLab,b)]||0))[0];start(currentLab,next,false,false)});$('#retryBtn').addEventListener('click',()=>session.training?start(session.lastLab,null,true,session.globalTraining):start(session.lastLab,session.lastMode,false,false));
  renderLabs();updateHeader();
})();

